---
title: "Lodgepole Forest"
author: "Katherine Frazer"
date: "2024-10-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source("setup.R")
```

# 2024 Ground Cover

Dataset

```{r}
lp_cover_2024 <- read_excel("../data/clean/lodgepole_forest.xlsx", 
                            sheet = "F24 % Cover", 
                            range = "A1:J11")
View(lp_cover_2024)
```

Tidy

```{r}
lp_cover_2024_tidy <- lp_cover_2024 %>% 
  select(1, 3:9) %>%
  pivot_longer(!Transect, 
               names_to = "GroundCover",
               values_to = "Percentage")
```

Graph

```{r}
lp_cover_2024_tidy %>%
  ggplot(aes(x = Transect, y = Percentage)) +
  geom_col(aes(fill = GroundCover)) +
  labs(title = "Ground Cover Type Percentage in 2024",
       subtitle = "Location: Lodgepole Forest, CSU Mountain Campus, CO",
       caption = "Due to collection errors, Transects 4, 7, and 10 do not add up to 100%.",
       x = "Transect Number",
       y = "Percentage of Cover Type") +
  guides(fill = guide_legend(title = "Cover Type")) +
  dark_theme_minimal() +
  scale_fill_viridis(discrete = TRUE) +
  scale_x_continuous(breaks = seq(1, 10, by = 1)) +
  theme(legend.position = "right",
        plot.title = element_text(face = "bold", size = "20"),
        plot.title.position = "plot",
        axis.title.x = element_text(face = "bold", size = "10"),
        axis.title.y = element_text(face = "bold", size = "10"))
```

# 2024 Trees

# Historical Frequency

Data

```{r}
lp_hf <- read_excel("../data/clean/lodgepole_forest.xlsx", 
    sheet = "Historical Frequency", range = "A2:K10", 
    na = "x")
View(lp_hf)
```

Tidy

```{r}
lp_hf_tidy <- lp_hf %>% 
  select(!c(2, 6)) %>%
  pivot_longer(!GroundCover,
               names_to = "Year",
               values_to = "Percentage")
```

Graph

```{r}
# this graph is better for comparing full cover types
lp_hf_tidy %>%
  ggplot(aes(x = Year, y = Percentage)) +
  geom_col(aes(fill = GroundCover)) +
  labs(title = "Historical Ground Cover Frequency",
       subtitle = "Location: Lodgepole Forest, CSU Mountain Campus, CO",
       x = "Year",
       y = "Percentage of Quadrats") +
  guides(fill = guide_legend(title = "Cover Type")) +
  dark_theme_minimal() +
  scale_fill_viridis(discrete = TRUE) +
  theme(plot.title = element_text(face = "bold", size = "20"),
        plot.title.position = "plot", 
        axis.text.y = element_text(size = "7.5"))

# annotate the 1999 year
```

```{r}
lp_hf_tidy %>%
  group_by(GroundCover) %>%
  ggplot(aes(x = Year, y = Percentage)) +
  geom_point(aes(color = GroundCover)) +
  facet_wrap(~GroundCover, ncol = 2) +
  geom_line(aes(color = GroundCover), group = 1) +
  labs(title = "Historical Ground Cover Frequency",
       subtitle = "Location: Lodgepole Forest, CSU Mountain Campus, CO",
       x = "Year",
       y = "Percentage of Quadrats") +
  dark_theme_gray() +
  scale_color_viridis(discrete = TRUE) +
  theme(legend.position = "none",
        plot.title = element_text(face = "bold", size = "20"),
        plot.title.position = "plot", 
        axis.text.x = element_text(angle = 20),
        axis.text.y = element_text(size = "7", angle = 0))
```

# Historical Relative Frequency

Data

```{r}
lp_hrf <- read_excel("../data/clean/lodgepole_forest.xlsx", 
    sheet = "Historical Relative Freq", range = "A2:K10", 
    na = "x")
View(lp_hrf)
```

Tidy

```{r}
lp_hrf_tidy <- lp_hrf %>%
  select(!c(2,6)) %>%
  pivot_longer(!GroundCover,
               names_to = "Year",
               values_to = "Percentage")
```

Graph

```{r}
# generate graph similar to that in historical frequency section
lp_hrf_tidy %>%
  ggplot(aes(x = Year, y = Percentage)) +
  geom_col(aes(fill = GroundCover)) +
  labs(title = "Historical Ground Cover Relative Frequency",
       subtitle = "Location: Lodgepole Forest, CSU Mountain Campus, CO",
       y = "Relative Frequency (%)") +
  guides(fill = guide_legend(title = "Cover Type")) +
  dark_theme_minimal() +
  scale_fill_viridis(discrete = TRUE) +
  theme(plot.title = element_text(face = "bold", size = "19"),
        plot.title.position = "plot", 
        axis.text.y = element_text(size = "7.5"))
```

# Historical Average Percent Cover

Data

```{r}
lp_havg <- read_excel("../data/clean/lodgepole_forest.xlsx", 
    sheet = "Historical Avg % Cover", range = "A2:K10", 
    na = "x")
View(lp_havg)
```

Tidy

```{r}
lp_havg_tidy <- lp_havg %>%
  select(!c(2,6)) %>%
  pivot_longer(!GroundCover,
               names_to = "Year",
               values_to = "Percentage")
```

Graph

```{r}
# generate graph similar to all above
lp_havg_tidy %>%
  ggplot(aes(x = Year, y = Percentage)) +
  geom_col(aes(fill = GroundCover)) +
  labs(title = "Historical Average Percent Ground Cover",
       subtitle = "Location: Lodgepole Forest, CSU Mountain Campus, CO",
       x = "Year",
       y = "Average Ground Cover (%)") +
  guides(fill = guide_legend(title = "Cover Type")) +
  dark_theme_gray() +
  scale_fill_viridis(discrete = TRUE) +
  theme(legend.position = "right",
        plot.title = element_text(face = "bold", size = "20"),
        plot.title.position = "plot", 
        axis.text.x = element_text(angle = 20),
        axis.text.y = element_text(size = "7", angle = 0))
```
